- name: Instalação do Jenkins
  hosts: jenkins
  remote_user: root
  tasks:
  - name: Instalação do Java
    ansible.builtin.apt:
      name: openjdk-11-jdk
      state: present
      update_cache: yes
  - name: Adicionando a chave do repositorio do Jenkins
    ansible.builtin.apt_key:
      url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
      state: present
  - name: Adicionando o repositorio do Jenkins 
    ansible.builtin.apt_repository: 
      repo: deb https://pkg.jenkins.io/debian-stable binary/
      state: present 
  - name: Instalação do Jenkins
    ansible.builtin.apt:
      name: jenkins
      state: present
      update_cache: yes

  - name: Obtendo a chave initialAdminPassword do Jenkins
    ansible.builtin.command: cat /var/lib/jenkins/secrets/initialAdminPassword
    register: chave
    ignore_errors: yes

  - name: Exibindo a chave initialAdminPassword
    ansible.builtin.debug:
      msg: "{{ chave.stdout }}"
    when: chave.stdout != ""

- name: Instalação do Docker
  hosts: jenkins
  remote_user: root
  tasks:
  - name: Instalação de pré-requisitos
    apt:
      name: ca-certificates, curl, gnupg, lsb-release
      state: present
      update_cache: yes

  - name: Adicionando a chave do repositório do Docker
    ansible.builtin.apt_key: 
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present  

  - name: Adicionando o repositorio do Docker 
    ansible.builtin.apt_repository: 
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present 

  - name: Instalação do Docker
    ansible.builtin.apt:
      name: docker-ce, docker-ce-cli, containerd.io
      state: present
      update_cache: yes

  - name: Adicionando o usuário jenkins no grupo docker
    ansible.builtin.user:
      name: jenkins
      groups: docker
      state: present
      append: yes

  - name: Restart do jenkins
    ansible.builtin.service:
      name: jenkins
      state: restarted

- name: Instalação do kubectl
  hosts: jenkins
  remote_user: root
  tasks:
  - name: Instalação de pré-requisitos 
    ansible.builtin.apt:
      name: ca-certificates, curl
      state: present
      update_cache: yes

  - name: Adicionando a chave do repositório do Kubernetes
    ansible.builtin.apt_key: 
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present  

  - name: Adicionando o repositorio do Kubernetes
    ansible.builtin.apt_repository: 
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present 

  - name: Instalação do Kubectl 
    ansible.builtin.apt:
      name: kubectl
      state: present
      update_cache: yes

